// Import images
// import { apple, banana, firstAidKit, cake, gunBackpack, gun, binoculars, handcuffs, helmet, sniper, poloShirt, shirt } from './images/Items/ItemImages';
import { gadgetParachute, acidpackage, advancedrifle, appistol, assaultrifle, assaultrifleMk2, assaultshotgun, assaultsmg, autoshotgun, ball, bat, battleaxe, bottle, bullpuprifle, bullpuprifleMk2, bullpupshotgun, bzgas, candycane, carbinerifle, carbinerifleMk2, ceramicpistol, combatmg, combatmgMk2, combatpdw, combatpistol, combatshotgun, compactlauncher, compactrifle, crowbar, dagger, dbshotgun, doubleaction, emplauncher, fertilizercan, fireextinguisher, firework, flare, flaregun, flashlight, gadgetpistol, golfclub, grenade, grenadelauncher, grenadelauncherSmoke, gusenberg, hammer, hatchet, hazardcan, heavypistol, heavyrifle, heavyshotgun, heavysniper, heavysniperMk2, hominglauncher, knife, knuckle, machete, machinepistol, marksmanpistol, marksmanrifle, marksmanrifleMk2, mg, microsmg, militaryrifle, minigun, minismg, molotov, musket, navyrevolver, nightstick, petrolcan, pipebomb, pistol, pistol50, pistolxm3, pistolMk2, poolcue, precisionrifle, proxmine, pumpshotgun, pumpshotgunMk2, railgun, railgunxm3, raycarbine, rayminigun, raypistol, revolver, revolverMk2, rpg, sawnoffshotgun, smg, smgMk2, smokegrenade, sniperrifle, snowball, snspistol, snspistolMk2, specialcarbine, specialcarbineMk2, stickybomb, stoneHatchet, stungun, stungunMp, switchblade, tacticalrifle, tecpistol, unarmed, vintagepistol, wrench } from './images/Items/ItemImages';

// Mapping of items to their images
export const ItemMapping = {
  // "Apple": { image: apple },
  // "Banana": { image: banana },
  // "First Aid Kit": { image: firstAidKit },
  // "Free Cake": { image: cake },
  // "Gun Backpack": { image: gunBackpack },
  // "Gun": { image: gun },
  // "Binoculars": { image: binoculars },
  // "Handcuffs": { image: handcuffs },
  // "Helmet": { image: helmet },
  // "Sniper": { image: sniper },
  // "Polo Shirt": { image: poloShirt },
  // "Shirt": { image: shirt },

  // Weapon items mapping
  "Gadget Parachute": { image: gadgetParachute },
  "Acid Package": { image: acidpackage },
  "Advanced Rifle": { image: advancedrifle },
  "AP Pistol": { image: appistol },
  "Assault Rifle": { image: assaultrifle },
  "Assault Rifle Mk2": { image: assaultrifleMk2 },
  "Assault Shotgun": { image: assaultshotgun },
  "Assault SMG": { image: assaultsmg },
  "Auto Shotgun": { image: autoshotgun },
  "Ball": { image: ball },
  "Bat": { image: bat },
  "Battleaxe": { image: battleaxe },
  "Bottle": { image: bottle },
  "Bullpup Rifle": { image: bullpuprifle },
  "Bullpup Rifle Mk2": { image: bullpuprifleMk2 },
  "Bullpup Shotgun": { image: bullpupshotgun },
  "BZ Gas": { image: bzgas },
  "Candy Cane": { image: candycane },
  "Carbine Rifle": { image: carbinerifle },
  "Carbine Rifle Mk2": { image: carbinerifleMk2 },
  "Ceramic Pistol": { image: ceramicpistol },
  "Combat MG": { image: combatmg },
  "Combat MG Mk2": { image: combatmgMk2 },
  "Combat PDW": { image: combatpdw },
  "Combat Pistol": { image: combatpistol },
  "Combat Shotgun": { image: combatshotgun },
  "Compact Launcher": { image: compactlauncher },
  "Compact Rifle": { image: compactrifle },
  "Crowbar": { image: crowbar },
  "Dagger": { image: dagger },
  "DB Shotgun": { image: dbshotgun },
  "Double Action": { image: doubleaction },
  "EMP Launcher": { image: emplauncher },
  "Fertilizer Can": { image: fertilizercan },
  "Fire Extinguisher": { image: fireextinguisher },
  "Firework": { image: firework },
  "Flare": { image: flare },
  "Flare Gun": { image: flaregun },
  "Flashlight": { image: flashlight },
  "Gadget Pistol": { image: gadgetpistol },
  "Golf Club": { image: golfclub },
  "Grenade": { image: grenade },
  "Grenade Launcher": { image: grenadelauncher },
  "Grenade Launcher (Smoke)": { image: grenadelauncherSmoke },
  "Gusenberg": { image: gusenberg },
  "Hammer": { image: hammer },
  "Hatchet": { image: hatchet },
  "Hazard Can": { image: hazardcan },
  "Heavy Pistol": { image: heavypistol },
  "Heavy Rifle": { image: heavyrifle },
  "Heavy Shotgun": { image: heavyshotgun },
  "Heavy Sniper": { image: heavysniper },
  "Heavy Sniper Mk2": { image: heavysniperMk2 },
  "Homing Launcher": { image: hominglauncher },
  "Knife": { image: knife },
  "Knuckle": { image: knuckle },
  "Machete": { image: machete },
  "Machine Pistol": { image: machinepistol },
  "Marksman Pistol": { image: marksmanpistol },
  "Marksman Rifle": { image: marksmanrifle },
  "Marksman Rifle Mk2": { image: marksmanrifleMk2 },
  "MG": { image: mg },
  "Micro SMG": { image: microsmg },
  "Military Rifle": { image: militaryrifle },
  "Minigun": { image: minigun },
  "Mini SMG": { image: minismg },
  "Molotov": { image: molotov },
  "Musket": { image: musket },
  "Navy Revolver": { image: navyrevolver },
  "Nightstick": { image: nightstick },
  "Petrol Can": { image: petrolcan },
  "Pipe Bomb": { image: pipebomb },
  "Pistol": { image: pistol },
  "Pistol 50": { image: pistol50 },
  "Pistol XM3": { image: pistolxm3 },
  "Pistol Mk2": { image: pistolMk2 },
  "Pool Cue": { image: poolcue },
  "Precision Rifle": { image: precisionrifle },
  "Proximity Mine": { image: proxmine },
  "Pump Shotgun": { image: pumpshotgun },
  "Pump Shotgun Mk2": { image: pumpshotgunMk2 },
  "Railgun": { image: railgun },
  "Railgun XM3": { image: railgunxm3 },
  "Ray Carbine": { image: raycarbine },
  "Ray Minigun": { image: rayminigun },
  "Ray Pistol": { image: raypistol },
  "Revolver": { image: revolver },
  "Revolver Mk2": { image: revolverMk2 },
  "RPG": { image: rpg },
  "Sawed-Off Shotgun": { image: sawnoffshotgun },
  "SMG": { image: smg },
  "SMG Mk2": { image: smgMk2 },
  "Smoke Grenade": { image: smokegrenade },
  "Sniper Rifle": { image: sniperrifle },
  "Snowball": { image: snowball },
  "SNS Pistol": { image: snspistol },
  "SNS Pistol Mk2": { image: snspistolMk2 },
  "Special Carbine": { image: specialcarbine },
  "Special Carbine Mk2": { image: specialcarbineMk2 },
  "Sticky Bomb": { image: stickybomb },
  "Stone Hatchet": { image: stoneHatchet },
  "Stun Gun": { image: stungun },
  "Stun Gun MP": { image: stungunMp },
  "Switchblade": { image: switchblade },
  "Tactical Rifle": { image: tacticalrifle },
  "Tec Pistol": { image: tecpistol },
  "Unarmed": { image: unarmed },
  "Vintage Pistol": { image: vintagepistol },
  "Wrench": { image: wrench }
};
